sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sariroti/docker-react-multicontainer-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t sariroti/docker-react-multicontainer-client ./client
  - docker build -t sariroti/docker-react-multicontainer-nginx ./nginx
  - docker build -t sariroti/docker-react-multicontainer-server ./server
  - docker build -t sariroti/docker-react-multicontainer-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sariroti/docker-react-multicontainer-client
  - docker push sariroti/docker-react-multicontainer-nginx
  - docker push sariroti/docker-react-multicontainer-server
  - docker push sariroti/docker-react-multicontainer-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-673905232157'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
